services:
  db:
    container_name: tefas_db
    image: postgres:15.5
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fund
    volumes:
      - ../backend/data/db/:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d fund"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    container_name: tefas_backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fund
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SERVER_PORT: 8081
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"
    shm_size: "1gb"
    restart: unless-stopped

  pgadmin:
    container_name: tefas-pgadmin
    image: dpage/pgadmin4:8.9
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - data-pgadmin-service:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  data-pgadmin-service:
