services:
  db:
    container_name: tefas_db
    image: postgres:15.5
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fund
    volumes:
      - ../data/db/:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    restart: unless-stopped

  pgadmin:
    container_name: tefas-pgadmin
    image: dpage/pgadmin4:8.9
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - data-pgadmin-service:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  data-pgadmin-service: